// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/portworx/px-loki/client/apis/loki/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// PXIssueLister helps list PXIssues.
// All objects returned here must be treated as read-only.
type PXIssueLister interface {
	// List lists all PXIssues in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.PXIssue, err error)
	// Get retrieves the PXIssue from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.PXIssue, error)
	PXIssueListerExpansion
}

// pXIssueLister implements the PXIssueLister interface.
type pXIssueLister struct {
	indexer cache.Indexer
}

// NewPXIssueLister returns a new PXIssueLister.
func NewPXIssueLister(indexer cache.Indexer) PXIssueLister {
	return &pXIssueLister{indexer: indexer}
}

// List lists all PXIssues in the indexer.
func (s *pXIssueLister) List(selector labels.Selector) (ret []*v1alpha1.PXIssue, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.PXIssue))
	})
	return ret, err
}

// Get retrieves the PXIssue from the index for a given name.
func (s *pXIssueLister) Get(name string) (*v1alpha1.PXIssue, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("pxissue"), name)
	}
	return obj.(*v1alpha1.PXIssue), nil
}
