// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/portworx/px-loki/client/clientset/versioned/typed/loki/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeAutopilotV1alpha1 struct {
	*testing.Fake
}

func (c *FakeAutopilotV1alpha1) PXIssues() v1alpha1.PXIssueInterface {
	return &FakePXIssues{c}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeAutopilotV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
