// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/portworx/px-loki/client/apis/loki/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakePXIssues implements PXIssueInterface
type FakePXIssues struct {
	Fake *FakeAutopilotV1alpha1
}

var pxissuesResource = schema.GroupVersionResource{Group: "autopilot.libopenstorage.org", Version: "v1alpha1", Resource: "pxissues"}

var pxissuesKind = schema.GroupVersionKind{Group: "autopilot.libopenstorage.org", Version: "v1alpha1", Kind: "PXIssue"}

// Get takes name of the pXIssue, and returns the corresponding pXIssue object, and an error if there is any.
func (c *FakePXIssues) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.PXIssue, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(pxissuesResource, name), &v1alpha1.PXIssue{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PXIssue), err
}

// List takes label and field selectors, and returns the list of PXIssues that match those selectors.
func (c *FakePXIssues) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.PXIssueList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(pxissuesResource, pxissuesKind, opts), &v1alpha1.PXIssueList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.PXIssueList{ListMeta: obj.(*v1alpha1.PXIssueList).ListMeta}
	for _, item := range obj.(*v1alpha1.PXIssueList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested pXIssues.
func (c *FakePXIssues) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(pxissuesResource, opts))
}

// Create takes the representation of a pXIssue and creates it.  Returns the server's representation of the pXIssue, and an error, if there is any.
func (c *FakePXIssues) Create(ctx context.Context, pXIssue *v1alpha1.PXIssue, opts v1.CreateOptions) (result *v1alpha1.PXIssue, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(pxissuesResource, pXIssue), &v1alpha1.PXIssue{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PXIssue), err
}

// Update takes the representation of a pXIssue and updates it. Returns the server's representation of the pXIssue, and an error, if there is any.
func (c *FakePXIssues) Update(ctx context.Context, pXIssue *v1alpha1.PXIssue, opts v1.UpdateOptions) (result *v1alpha1.PXIssue, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(pxissuesResource, pXIssue), &v1alpha1.PXIssue{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PXIssue), err
}

// Delete takes name of the pXIssue and deletes it. Returns an error if one occurs.
func (c *FakePXIssues) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(pxissuesResource, name), &v1alpha1.PXIssue{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakePXIssues) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(pxissuesResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.PXIssueList{})
	return err
}

// Patch applies the patch and returns the patched pXIssue.
func (c *FakePXIssues) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.PXIssue, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(pxissuesResource, name, pt, data, subresources...), &v1alpha1.PXIssue{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PXIssue), err
}
