// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	lokiv1alpha1 "github.com/portworx/px-loki/client/apis/loki/v1alpha1"
	versioned "github.com/portworx/px-loki/client/clientset/versioned"
	internalinterfaces "github.com/portworx/px-loki/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/portworx/px-loki/client/listers/loki/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// PXIssueInformer provides access to a shared informer and lister for
// PXIssues.
type PXIssueInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.PXIssueLister
}

type pXIssueInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewPXIssueInformer constructs a new informer for PXIssue type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewPXIssueInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredPXIssueInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredPXIssueInformer constructs a new informer for PXIssue type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredPXIssueInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AutopilotV1alpha1().PXIssues().List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AutopilotV1alpha1().PXIssues().Watch(context.TODO(), options)
			},
		},
		&lokiv1alpha1.PXIssue{},
		resyncPeriod,
		indexers,
	)
}

func (f *pXIssueInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredPXIssueInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *pXIssueInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&lokiv1alpha1.PXIssue{}, f.defaultInformer)
}

func (f *pXIssueInformer) Lister() v1alpha1.PXIssueLister {
	return v1alpha1.NewPXIssueLister(f.Informer().GetIndexer())
}
